### ISSUE TITLE
Tracking issue: update default config

### ISSUE THREAD

**Issue by tomasciccola** [digidem/mapeo-default-config#43]
- [ ]  #40 
- [ ] https://github.com/digidem/mapeo-settings-builder/pull/53
- [ ] https://github.com/digidem/mapeo-default-config/issues/39
- [ ] https://github.com/digidem/mapeo-core-next/issues/496
